import { FormFieldTemplate, FormFieldType } from './types/industry-templates';

export interface PredefinedFieldItem {
  id: string;
  name: string;
  key: string;
  label: string;
  type: FormFieldType;
  category: 'System' | 'Custom';
  module: string; // e.g. "Clients", "Appointments", "Call Logs", "Processes", "Organisation", "Products / Services"
  industry?: string; // e.g. "Dental Practice", "Cardiology Specialist", "Personal Injury Law", "Residential Real Estate", "HVAC & Home Services", "Auto Dealership & Service", "SaaS / IT Consulting", "Executive Coaching", "All"
  description?: string;
  placeholder?: string;
  helperText?: string;
  isRequired?: boolean;
  options?: { label: string; value: string }[];
  crmFieldMapping: string;
}

export interface IndustryOption {
  id: string;
  name: string;
  category: string;
  icon: string;
}

export const AVAILABLE_INDUSTRIES_LIST: IndustryOption[] = [
  { id: 'ind-general', name: 'General / Universal', category: 'Cross-Industry', icon: 'Briefcase' },
  { id: 'ind-dental', name: 'Dental Practice', category: 'Healthcare & Medical', icon: 'Stethoscope' },
  { id: 'ind-cardio', name: 'Cardiology Specialist', category: 'Healthcare & Medical', icon: 'Activity' },
  { id: 'ind-legal', name: 'Personal Injury Law', category: 'Legal & Professional', icon: 'Scale' },
  { id: 'ind-realestate', name: 'Residential Real Estate', category: 'Real Estate & Property', icon: 'Home' },
  { id: 'ind-hvac', name: 'HVAC & Home Services', category: 'Home Services & Contracting', icon: 'Wrench' },
  { id: 'ind-auto', name: 'Auto Dealership & Service', category: 'Automotive & Transport', icon: 'Car' },
  { id: 'ind-tech', name: 'SaaS / IT Consulting', category: 'IT & Cloud Services', icon: 'Cpu' },
  { id: 'ind-coaching', name: 'Executive Coaching', category: 'Coaching & Advisory', icon: 'Sparkles' },
];

// ==========================================
// 1. STANDARD CRM SYSTEM FIELDS (UNIVERSAL)
// ==========================================
export const SYSTEM_FIELDS: PredefinedFieldItem[] = [
  // --- Clients & Contact Info ---
  {
    id: 'sys-full-name',
    name: 'Full Name',
    label: 'Full Name',
    key: 'full_name',
    type: 'text',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'Complete legal name of the client or patient',
    placeholder: 'e.g. John Doe',
    isRequired: true,
    crmFieldMapping: 'client_name',
  },
  {
    id: 'sys-first-name',
    name: 'First Name',
    label: 'First Name',
    key: 'first_name',
    type: 'text',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'First given name',
    placeholder: 'e.g. John',
    crmFieldMapping: 'first_name',
  },
  {
    id: 'sys-last-name',
    name: 'Last Name',
    label: 'Last Name',
    key: 'last_name',
    type: 'text',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'Family or surname',
    placeholder: 'e.g. Doe',
    crmFieldMapping: 'last_name',
  },
  {
    id: 'sys-email',
    name: 'Email Address',
    label: 'Email Address',
    key: 'email',
    type: 'email',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'Primary contact email for correspondence and notifications',
    placeholder: 'name@example.com',
    isRequired: true,
    crmFieldMapping: 'client_email',
  },
  {
    id: 'sys-phone',
    name: 'Phone Number',
    label: 'Phone Number',
    key: 'phone',
    type: 'phone',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'Primary telephone/mobile number with SMS capability',
    placeholder: '+1 (555) 000-0000',
    isRequired: true,
    crmFieldMapping: 'client_phone',
  },
  {
    id: 'sys-alt-phone',
    name: 'Alternative Phone',
    label: 'Alternative Phone',
    key: 'alt_phone',
    type: 'phone',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'Secondary or emergency backup contact number',
    placeholder: '+1 (555) 123-4567',
    crmFieldMapping: 'alt_phone',
  },
  {
    id: 'sys-dob',
    name: 'Date of Birth',
    label: 'Date of Birth',
    key: 'dob',
    type: 'date',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'Client date of birth for records and verification',
    placeholder: 'YYYY-MM-DD',
    crmFieldMapping: 'client_dob',
  },
  {
    id: 'sys-gender',
    name: 'Gender',
    label: 'Gender',
    key: 'gender',
    type: 'select',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'Gender identity',
    options: [
      { label: 'Male', value: 'male' },
      { label: 'Female', value: 'female' },
      { label: 'Non-binary', value: 'non_binary' },
      { label: 'Prefer not to say', value: 'prefer_not_to_say' },
    ],
    crmFieldMapping: 'client_gender',
  },
  {
    id: 'sys-address',
    name: 'Street Address',
    label: 'Street Address',
    key: 'address',
    type: 'text',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'Primary residential or business street address',
    placeholder: '123 Main Street, Suite 400',
    crmFieldMapping: 'client_address',
  },
  {
    id: 'sys-city',
    name: 'City',
    label: 'City',
    key: 'city',
    type: 'text',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'City or municipality',
    placeholder: 'e.g. New York',
    crmFieldMapping: 'client_city',
  },
  {
    id: 'sys-state',
    name: 'State / Province',
    label: 'State / Province',
    key: 'state',
    type: 'text',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'State, province, or region',
    placeholder: 'e.g. NY or California',
    crmFieldMapping: 'client_state',
  },
  {
    id: 'sys-zip',
    name: 'Postal / Zip Code',
    label: 'Postal / Zip Code',
    key: 'zip_code',
    type: 'text',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'Postal or zip code',
    placeholder: 'e.g. 10001',
    crmFieldMapping: 'client_zip',
  },
  {
    id: 'sys-company',
    name: 'Company / Organization',
    label: 'Company / Organization',
    key: 'company_name',
    type: 'text',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'Client company or workplace name',
    placeholder: 'e.g. Acme Corporation',
    crmFieldMapping: 'company_name',
  },
  {
    id: 'sys-job-title',
    name: 'Job Title / Role',
    label: 'Job Title / Role',
    key: 'job_title',
    type: 'text',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'Professional title or role in organization',
    placeholder: 'e.g. VP of Operations',
    crmFieldMapping: 'job_title',
  },

  // --- Appointments & Scheduling ---
  {
    id: 'sys-appt-date',
    name: 'Preferred Appointment Date',
    label: 'Preferred Appointment Date',
    key: 'appointment_date',
    type: 'date',
    category: 'System',
    module: 'Appointments',
    industry: 'All',
    description: 'Requested date for appointment or consultation',
    isRequired: true,
    crmFieldMapping: 'appointment_date',
  },
  {
    id: 'sys-appt-time',
    name: 'Preferred Time Slot',
    label: 'Preferred Time Slot',
    key: 'appointment_time',
    type: 'text',
    category: 'System',
    module: 'Appointments',
    industry: 'All',
    description: 'Preferred appointment time window',
    placeholder: 'e.g. 10:00 AM or Morning (9am - 12pm)',
    crmFieldMapping: 'appointment_time',
  },
  {
    id: 'sys-consultation-type',
    name: 'Consultation Type',
    label: 'Consultation Type',
    key: 'consultation_type',
    type: 'select',
    category: 'System',
    module: 'Appointments',
    industry: 'All',
    description: 'Format of consultation (in-person, virtual video, or phone)',
    options: [
      { label: 'In-Person Office Visit', value: 'in_person' },
      { label: 'Virtual Telehealth / Video Call', value: 'video_call' },
      { label: 'Phone Consultation', value: 'phone_call' },
    ],
    crmFieldMapping: 'consultation_type',
  },
  {
    id: 'sys-assigned-staff',
    name: 'Assigned Staff / Provider',
    label: 'Assigned Staff / Provider',
    key: 'assigned_provider',
    type: 'select',
    category: 'System',
    module: 'Appointments',
    industry: 'All',
    description: 'Target practitioner, doctor, or agent assigned to this booking',
    options: [
      { label: 'First Available Specialist', value: 'any_available' },
      { label: 'Senior Consultant', value: 'senior_consultant' },
      { label: 'Staff Specialist', value: 'staff_specialist' },
    ],
    crmFieldMapping: 'assigned_provider',
  },
  {
    id: 'sys-chief-complaint',
    name: 'Chief Complaint / Reason for Visit',
    label: 'Reason for Visit / Chief Complaint',
    key: 'chief_complaint',
    type: 'textarea',
    category: 'System',
    module: 'Appointments',
    industry: 'All',
    description: 'Primary problem, symptom, or objective of inquiry',
    placeholder: 'Describe your symptoms, concern, or goals in detail...',
    isRequired: true,
    crmFieldMapping: 'chief_complaint',
  },
  {
    id: 'sys-appt-notes',
    name: 'Special Instructions / Notes',
    label: 'Special Instructions / Notes',
    key: 'appointment_notes',
    type: 'textarea',
    category: 'System',
    module: 'Appointments',
    industry: 'All',
    description: 'Any accessibility requirements, notes, or dietary constraints',
    placeholder: 'Any special requests or additional information...',
    crmFieldMapping: 'appointment_notes',
  },

  // --- Call Logs & Inbound Triage ---
  {
    id: 'sys-preferred-callback',
    name: 'Preferred Callback Window',
    label: 'Preferred Callback Window',
    key: 'preferred_callback_time',
    type: 'text',
    category: 'System',
    module: 'Call Logs',
    industry: 'All',
    description: 'Best time for our AI or agent team to call the client back',
    placeholder: 'e.g. Weekdays between 2:00 PM – 5:00 PM',
    crmFieldMapping: 'preferred_callback_time',
  },
  {
    id: 'sys-contact-method',
    name: 'Preferred Contact Method',
    label: 'Preferred Contact Method',
    key: 'contact_method',
    type: 'select',
    category: 'System',
    module: 'Call Logs',
    industry: 'All',
    description: 'Client preferred channel of communication',
    options: [
      { label: 'Phone Call', value: 'phone' },
      { label: 'Email', value: 'email' },
      { label: 'SMS Text Message', value: 'sms' },
      { label: 'WhatsApp', value: 'whatsapp' },
    ],
    crmFieldMapping: 'preferred_contact_channel',
  },
  {
    id: 'sys-urgency-level',
    name: 'Urgency / Triage Level',
    label: 'Urgency Level',
    key: 'urgency_level',
    type: 'select',
    category: 'System',
    module: 'Call Logs',
    industry: 'All',
    description: 'Priority level for lead routing and response SLAs',
    options: [
      { label: 'Standard (Within 24-48 hours)', value: 'standard' },
      { label: 'Urgent (Same Day Response)', value: 'urgent' },
      { label: 'Emergency / Immediate Dispatch', value: 'immediate' },
    ],
    crmFieldMapping: 'lead_urgency',
  },
  {
    id: 'sys-referral-source',
    name: 'How Did You Hear About Us',
    label: 'Referral Source',
    key: 'referral_source',
    type: 'select',
    category: 'System',
    module: 'Call Logs',
    industry: 'All',
    description: 'Marketing attribution channel or referral source',
    options: [
      { label: 'Google Search', value: 'google' },
      { label: 'Social Media (Instagram/LinkedIn/Facebook)', value: 'social_media' },
      { label: 'Doctor / Physician Referral', value: 'doctor_referral' },
      { label: 'Friend or Family Member', value: 'word_of_mouth' },
      { label: 'Online Advertisement', value: 'online_ad' },
      { label: 'Other', value: 'other' },
    ],
    crmFieldMapping: 'referral_source',
  },

  // --- Financial, Billing & Verification ---
  {
    id: 'sys-insurance-provider',
    name: 'Insurance Provider Network',
    label: 'Insurance Provider Network',
    key: 'insurance_provider',
    type: 'text',
    category: 'System',
    module: 'Organisation',
    industry: 'All',
    description: 'Primary insurance carrier or network name',
    placeholder: 'e.g. Delta Dental, Blue Cross Blue Shield, MetLife, Cigna',
    crmFieldMapping: 'insurance_provider',
  },
  {
    id: 'sys-policy-id',
    name: 'Policy / Member ID Number',
    label: 'Policy / Member ID',
    key: 'policy_id',
    type: 'text',
    category: 'System',
    module: 'Organisation',
    industry: 'All',
    description: 'Insurance policy ID or subscriber number',
    placeholder: 'e.g. POL-987654321',
    crmFieldMapping: 'policy_id',
  },
  {
    id: 'sys-budget',
    name: 'Estimated Budget / Price Range',
    label: 'Estimated Budget',
    key: 'budget',
    type: 'select',
    category: 'System',
    module: 'Processes',
    industry: 'All',
    description: 'Client proposed budget or investment range',
    options: [
      { label: 'Under $1,000', value: 'under_1k' },
      { label: '$1,000 - $3,000', value: '1k_to_3k' },
      { label: '$3,000 - $7,500', value: '3k_to_7_5k' },
      { label: '$7,500 - $15,000', value: '7_5k_to_15k' },
      { label: '$15,000+', value: '15k_plus' },
    ],
    crmFieldMapping: 'deal_budget',
  },
  {
    id: 'sys-insurance-card',
    name: 'Insurance Card / ID Photo',
    label: 'Upload Insurance Card / ID',
    key: 'insurance_card_file',
    type: 'file',
    category: 'System',
    module: 'Organisation',
    industry: 'All',
    description: 'Photo or PDF of insurance card front & back',
    helperText: 'Upload a clear photo or PDF of your insurance card',
    crmFieldMapping: 'insurance_document_url',
  },
  {
    id: 'sys-signature',
    name: 'Consent & Electronic Signature',
    label: 'Client Electronic Signature',
    key: 'client_signature',
    type: 'signature',
    category: 'System',
    module: 'Clients',
    industry: 'All',
    description: 'Electronic signature verifying terms consent',
    helperText: 'Please draw your legal signature in the box above',
    isRequired: true,
    crmFieldMapping: 'signature_payload',
  },
];

// ==========================================
// 2. INDUSTRY-SPECIFIC CUSTOM FIELDS
// ==========================================
export const DEFAULT_CUSTOM_FIELDS: PredefinedFieldItem[] = [
  // --- Common Cross-Industry Custom Fields ---
  {
    id: 'cf-vip',
    name: 'VIP Account Flag',
    label: 'VIP Account Flag',
    key: 'is_vip_account',
    type: 'checkbox',
    category: 'Custom',
    module: 'Clients',
    industry: 'All',
    description: 'Priority flag for executive / VIP tier routing',
    options: [{ label: 'Mark as VIP Client', value: 'is_vip' }],
    crmFieldMapping: 'cf_is_vip_account',
  },
  {
    id: 'cf-sentiment',
    name: 'Customer Sentiment Score',
    label: 'Customer Sentiment Score',
    key: 'customer_sentiment_score',
    type: 'number',
    category: 'Custom',
    module: 'Call Logs',
    industry: 'All',
    description: 'AI sentiment index calculated from call transcripts',
    placeholder: '1 to 10',
    crmFieldMapping: 'cf_customer_sentiment_score',
  },
  {
    id: 'cf-branch-tax',
    name: 'Branch Tax ID',
    label: 'Branch Tax ID',
    key: 'branch_tax_id',
    type: 'text',
    category: 'Custom',
    module: 'Organisation',
    industry: 'All',
    description: 'Federal or state tax registration number',
    placeholder: 'e.g. XX-XXXXXXX',
    crmFieldMapping: 'cf_branch_tax_id',
  },

  // --- Dental Practice ---
  {
    id: 'cf-dental-anxiety',
    name: 'Dental Anxiety Level',
    label: 'Dental Anxiety Level',
    key: 'dental_anxiety_level',
    type: 'select',
    category: 'Custom',
    module: 'Clients',
    industry: 'Dental Practice',
    description: 'Patient comfort index to assess sedation candidate status',
    options: [
      { label: 'None / Relaxed', value: 'none' },
      { label: 'Mild Nervousness', value: 'mild' },
      { label: 'High Anxiety (Sedation Candidate)', value: 'high' },
    ],
    crmFieldMapping: 'cf_dental_anxiety_level',
  },
  {
    id: 'cf-premed',
    name: 'Requires Antibiotic Pre-Med',
    label: 'Requires Antibiotic Pre-Med',
    key: 'requires_premed',
    type: 'radio',
    category: 'Custom',
    module: 'Clients',
    industry: 'Dental Practice',
    description: 'Medical alert for prophylactic antibiotics prior to dental cleanings',
    options: [
      { label: 'Yes, requires pre-medication', value: 'yes' },
      { label: 'No pre-medication needed', value: 'no' },
    ],
    crmFieldMapping: 'cf_requires_premed',
  },
  {
    id: 'cf-dentist-assigned',
    name: 'Dentist / Hygienist Assigned',
    label: 'Doctor Assigned',
    key: 'doctor_assigned',
    type: 'select',
    category: 'Custom',
    module: 'Appointments',
    industry: 'Dental Practice',
    description: 'Designated dental surgeon or hygienist',
    options: [
      { label: 'Dr. Evans (Lead Dentist)', value: 'dr_evans' },
      { label: 'Dr. Sarah Patel (Orthodontics)', value: 'dr_patel' },
      { label: 'Hygienist Miller', value: 'hygienist_miller' },
    ],
    isRequired: true,
    crmFieldMapping: 'cf_doctor_assigned',
  },

  // --- Cardiology Specialist ---
  {
    id: 'cf-pacemaker',
    name: 'Has Pacemaker / ICD Device',
    label: 'Has Pacemaker / Cardiac Device',
    key: 'has_pacemaker',
    type: 'radio',
    category: 'Custom',
    module: 'Clients',
    industry: 'Cardiology Specialist',
    description: 'Clinical safety contraindication for electromagnetic equipment',
    options: [
      { label: 'Yes, has implanted cardiac device', value: 'yes' },
      { label: 'No cardiac implants', value: 'no' },
    ],
    crmFieldMapping: 'cf_has_pacemaker',
  },
  {
    id: 'cf-cardio-assigned',
    name: 'Cardiologist Assigned',
    label: 'Doctor Assigned',
    key: 'doctor_assigned',
    type: 'select',
    category: 'Custom',
    module: 'Appointments',
    industry: 'Cardiology Specialist',
    description: 'Designated cardiologist',
    options: [
      { label: 'Dr. Sharma, MD (Interventional)', value: 'dr_sharma' },
      { label: 'Dr. Emily Watson, MD (Electrophysiology)', value: 'dr_watson' },
    ],
    isRequired: true,
    crmFieldMapping: 'cf_doctor_assigned',
  },
  {
    id: 'cf-referring-dr',
    name: 'Referring Physician Name',
    label: 'Referring Physician Name',
    key: 'referring_dr',
    type: 'text',
    category: 'Custom',
    module: 'Clients',
    industry: 'Cardiology Specialist',
    description: 'Name of primary physician who referred patient',
    placeholder: 'e.g. Dr. Arthur Miller, MD',
    crmFieldMapping: 'cf_referring_dr',
  },
  {
    id: 'cf-hosp-loc',
    name: 'Hospital / Clinic Location',
    label: 'Hospital / Clinic Location',
    key: 'hospital_location',
    type: 'text',
    category: 'Custom',
    module: 'Clients',
    industry: 'Cardiology Specialist',
    description: 'Specific medical campus, branch, or clinic location',
    placeholder: 'e.g. Downtown Heart Center',
    crmFieldMapping: 'cf_hospital_location',
  },

  // --- SaaS / IT Consulting ---
  {
    id: 'cf-cloud-platform',
    name: 'Target Cloud Platform',
    label: 'Target Cloud Platform',
    key: 'cloud_platform',
    type: 'select',
    category: 'Custom',
    module: 'Processes',
    industry: 'SaaS / IT Consulting',
    description: 'Cloud hosting environment',
    options: [
      { label: 'Amazon Web Services (AWS)', value: 'aws' },
      { label: 'Google Cloud Platform (GCP)', value: 'gcp' },
      { label: 'Microsoft Azure', value: 'azure' },
      { label: 'Hybrid Multi-Cloud', value: 'hybrid' },
      { label: 'On-Premise Private Cloud', value: 'on_prem' },
    ],
    crmFieldMapping: 'cf_cloud_platform',
  },
  {
    id: 'cf-tech-stack',
    name: 'Current Tech Stack',
    label: 'Current Tech Stack',
    key: 'tech_stack',
    type: 'text',
    category: 'Custom',
    module: 'Clients',
    industry: 'SaaS / IT Consulting',
    description: 'Frameworks, programming languages, or databases',
    placeholder: 'e.g. React, Next.js, Node.js, PostgreSQL',
    crmFieldMapping: 'cf_tech_stack',
  },
  {
    id: 'cf-project-timeline',
    name: 'Project Target Timeline',
    label: 'Project Target Timeline',
    key: 'project_timeline',
    type: 'select',
    category: 'Custom',
    module: 'Processes',
    industry: 'SaaS / IT Consulting',
    description: 'Delivery timeframe',
    options: [
      { label: 'Immediate Sprint (< 1 Month)', value: 'under_1_mo' },
      { label: '1 - 3 Months (Standard MVP)', value: '1_to_3_mo' },
      { label: '3 - 6 Months (Enterprise Rollout)', value: '3_to_6_mo' },
      { label: 'Long Term / Retainer Advisory', value: 'ongoing' },
    ],
    crmFieldMapping: 'cf_project_timeline',
  },
  {
    id: 'cf-compliance-goal',
    name: 'Compliance Audit Target',
    label: 'Compliance Audit Target',
    key: 'compliance_target',
    type: 'select',
    category: 'Custom',
    module: 'Processes',
    industry: 'SaaS / IT Consulting',
    description: 'Cybersecurity or regulatory standard',
    options: [
      { label: 'SOC2 Type II', value: 'soc2' },
      { label: 'HIPAA Compliance', value: 'hipaa' },
      { label: 'ISO 27001', value: 'iso27001' },
      { label: 'GDPR / Privacy Shield', value: 'gdpr' },
      { label: 'None / General Audit', value: 'none' },
    ],
    crmFieldMapping: 'cf_compliance_target',
  },

  // --- Auto Dealership & Service ---
  {
    id: 'cf-vehicle-vin',
    name: 'Vehicle VIN / Model',
    label: 'Vehicle VIN / Model',
    key: 'vehicle_model',
    type: 'text',
    category: 'Custom',
    module: 'Products / Services',
    industry: 'Auto Dealership & Service',
    description: 'Vehicle identification number and model trim',
    placeholder: 'e.g. 2024 Tesla Model Y / VIN# 1HGCR2...',
    crmFieldMapping: 'cf_vehicle_model',
  },
  {
    id: 'cf-vehicle-mileage',
    name: 'Current Mileage (Odometer)',
    label: 'Current Mileage',
    key: 'vehicle_mileage',
    type: 'number',
    category: 'Custom',
    module: 'Products / Services',
    industry: 'Auto Dealership & Service',
    description: 'Odometer reading in miles or kilometers',
    placeholder: 'e.g. 45000',
    crmFieldMapping: 'cf_vehicle_mileage',
  },
  {
    id: 'cf-auto-service-type',
    name: 'Auto Service Category',
    label: 'Auto Service Category',
    key: 'auto_service_type',
    type: 'select',
    category: 'Custom',
    module: 'Products / Services',
    industry: 'Auto Dealership & Service',
    description: 'Required vehicle service',
    options: [
      { label: 'Periodic Maintenance & Oil Change', value: 'maintenance' },
      { label: 'Brake, Suspension & Tire Service', value: 'brakes_tires' },
      { label: 'Engine / Transmission Diagnostics', value: 'engine_diag' },
      { label: 'Test Drive Scheduling (New Vehicle)', value: 'test_drive' },
      { label: 'Custom Paint & Accessories', value: 'customization' },
    ],
    crmFieldMapping: 'cf_auto_service_type',
  },
  {
    id: 'cf-tradein-flag',
    name: 'Trade-in Evaluation Interest',
    label: 'Trade-in Interest',
    key: 'has_trade_in',
    type: 'radio',
    category: 'Custom',
    module: 'Processes',
    industry: 'Auto Dealership & Service',
    description: 'Evaluating current car for dealership trade-in credit',
    options: [
      { label: 'Yes, evaluate my trade-in vehicle', value: 'yes' },
      { label: 'No trade-in', value: 'no' },
    ],
    crmFieldMapping: 'cf_has_trade_in',
  },

  // --- Residential Real Estate ---
  {
    id: 'cf-prop-type',
    name: 'Property Type Preference',
    label: 'Property Type Preference',
    key: 'property_type',
    type: 'select',
    category: 'Custom',
    module: 'Processes',
    industry: 'Residential Real Estate',
    description: 'Target real estate asset class',
    options: [
      { label: 'Single Family Residence', value: 'single_family' },
      { label: 'Luxury Condo / Penthouse', value: 'condo' },
      { label: 'Commercial Office Space', value: 'commercial' },
      { label: 'Multi-Family Investment', value: 'multi_family' },
    ],
    crmFieldMapping: 'cf_property_type',
  },
  {
    id: 'cf-preapproval-status',
    name: 'Mortgage Pre-Approval Status',
    label: 'Mortgage Pre-Approval Status',
    key: 'mortgage_status',
    type: 'select',
    category: 'Custom',
    module: 'Clients',
    industry: 'Residential Real Estate',
    description: 'Financing readiness',
    options: [
      { label: 'Pre-Approved with Letter', value: 'pre_approved' },
      { label: 'All-Cash Buyer', value: 'cash_buyer' },
      { label: 'Needs Mortgage Lender Introduction', value: 'needs_lender' },
      { label: 'Exploring Financing', value: 'exploring' },
    ],
    crmFieldMapping: 'cf_mortgage_status',
  },
  {
    id: 'cf-target-neighborhood',
    name: 'Target Neighborhood / Zip Code',
    label: 'Target Neighborhood',
    key: 'target_neighborhood',
    type: 'text',
    category: 'Custom',
    module: 'Processes',
    industry: 'Residential Real Estate',
    description: 'Desired location or school district',
    placeholder: 'e.g. Beverly Hills 90210, Downtown Loft District',
    crmFieldMapping: 'cf_target_neighborhood',
  },
  {
    id: 'cf-move-in-date',
    name: 'Target Move-in / Closing Date',
    label: 'Target Move-in Date',
    key: 'move_in_date',
    type: 'date',
    category: 'Custom',
    module: 'Appointments',
    industry: 'Residential Real Estate',
    description: 'Ideal closing or occupancy date',
    crmFieldMapping: 'cf_move_in_date',
  },

  // --- Personal Injury Law ---
  {
    id: 'cf-incident-date',
    name: 'Date of Incident / Accident',
    label: 'Date of Incident',
    key: 'incident_date',
    type: 'date',
    category: 'Custom',
    module: 'Clients',
    industry: 'Personal Injury Law',
    description: 'Date for statute of limitations tracking',
    crmFieldMapping: 'cf_incident_date',
  },
  {
    id: 'cf-injury-severity',
    name: 'Injury / Claim Severity',
    label: 'Claim Severity Level',
    key: 'claim_severity',
    type: 'select',
    category: 'Custom',
    module: 'Clients',
    industry: 'Personal Injury Law',
    description: 'Accident severity classification',
    options: [
      { label: 'Property Damage Only', value: 'property_only' },
      { label: 'Moderate Injury (Doctor Visited)', value: 'moderate' },
      { label: 'Severe (Hospitalization / Surgery)', value: 'severe' },
      { label: 'Catastrophic / Wrongful Death', value: 'catastrophic' },
    ],
    crmFieldMapping: 'cf_claim_severity',
  },
  {
    id: 'cf-opposing-party',
    name: 'Opposing Party / Company',
    label: 'Opposing Party / Company',
    key: 'opposing_party',
    type: 'text',
    category: 'Custom',
    module: 'Clients',
    industry: 'Personal Injury Law',
    description: 'Adverse entity for conflict checks',
    placeholder: 'e.g. City Transit Authority, ABC Insurance',
    crmFieldMapping: 'cf_opposing_party',
  },

  // --- Executive Coaching ---
  {
    id: 'cf-coaching-focus',
    name: 'Coaching Pillar Focus',
    label: 'Coaching Focus Area',
    key: 'coaching_focus',
    type: 'select',
    category: 'Custom',
    module: 'Clients',
    industry: 'Executive Coaching',
    description: 'Main mentorship track',
    options: [
      { label: 'Executive Leadership & C-Suite', value: 'executive' },
      { label: 'Career Transition & Salary Growth', value: 'career' },
      { label: 'Wealth, Investment & Financial Independence', value: 'wealth' },
      { label: 'Life, Mindset & Peak Performance', value: 'life_mindset' },
    ],
    crmFieldMapping: 'cf_coaching_focus',
  },
  {
    id: 'cf-income-band',
    name: 'Annual Revenue / Income Band',
    label: 'Income / Revenue Band',
    key: 'income_band',
    type: 'select',
    category: 'Custom',
    module: 'Clients',
    industry: 'Executive Coaching',
    description: 'Financial qualification tier',
    options: [
      { label: 'Under $100k', value: 'under_100k' },
      { label: '$100k - $250k', value: '100k_250k' },
      { label: '$250k - $500k', value: '250k_500k' },
      { label: '$500k - $1M+', value: '500k_plus' },
    ],
    crmFieldMapping: 'cf_income_band',
  },

  // --- HVAC & Home Services ---
  {
    id: 'cf-home-sqft',
    name: 'Property Area (Sq Ft)',
    label: 'Property Area (Sq Ft)',
    key: 'home_sqft',
    type: 'number',
    category: 'Custom',
    module: 'Clients',
    industry: 'HVAC & Home Services',
    description: 'Approximate square footage of home or property',
    placeholder: 'e.g. 2400',
    crmFieldMapping: 'cf_home_sqft',
  },
  {
    id: 'cf-system-age',
    name: 'Equipment / System Age',
    label: 'Equipment / System Age',
    key: 'system_age',
    type: 'select',
    category: 'Custom',
    module: 'Products / Services',
    industry: 'HVAC & Home Services',
    description: 'Age of AC, plumbing, or electrical unit',
    options: [
      { label: '< 2 Years (Under Warranty)', value: 'under_2yr' },
      { label: '3 - 7 Years (Standard Maintenance)', value: '3_to_7yr' },
      { label: '8 - 12 Years (Aging System)', value: '8_to_12yr' },
      { label: '12+ Years (Full Replacement Candidate)', value: '12yr_plus' },
    ],
    crmFieldMapping: 'cf_system_age',
  },
];

// Combine all fields
export const ALL_PREDEFINED_FIELDS: PredefinedFieldItem[] = [
  ...SYSTEM_FIELDS,
  ...DEFAULT_CUSTOM_FIELDS,
];

// Function to get predefined fields tailored for a specific selected industry
export function getPredefinedFieldsForIndustry(
  selectedIndustry?: string
): PredefinedFieldItem[] {
  if (!selectedIndustry || selectedIndustry.includes('General') || selectedIndustry.includes('Universal') || selectedIndustry === 'All') {
    return ALL_PREDEFINED_FIELDS;
  }

  const cleanSelected = selectedIndustry.toLowerCase().trim();

  return ALL_PREDEFINED_FIELDS.filter((item) => {
    if (!item.industry || item.industry === 'All') return true;
    const cleanItemIndustry = item.industry.toLowerCase().trim();
    return (
      cleanItemIndustry === cleanSelected ||
      cleanSelected.includes(cleanItemIndustry) ||
      cleanItemIndustry.includes(cleanSelected)
    );
  });
}

// Helper to convert a PredefinedFieldItem into a FormFieldTemplate instance
export function createFormFieldFromPredefined(
  item: PredefinedFieldItem
): FormFieldTemplate {
  const uniqueSuffix = Math.floor(1000 + Math.random() * 9000);
  return {
    id: `f-${item.key}-${Date.now()}-${uniqueSuffix}`,
    label: item.label,
    name: `${item.key}_${uniqueSuffix}`,
    type: item.type,
    placeholder: item.placeholder || '',
    helperText: item.helperText || item.description || '',
    isRequired: item.isRequired || false,
    options: item.options ? [...item.options] : undefined,
    crmFieldMapping: item.crmFieldMapping || item.key,
    fieldSource: item.category === 'System' ? 'system' : 'custom',
    sourceModule: item.module,
    systemFieldKey: item.key,
  };
}
